age:
  values:
  - дитина (0-12)
  - підліток (13-17)
  - молода особа (18-29)
  - доросла особа (30-44)
  - особа середнього віку (45-64)
  - особа похилого віку (65+)
  template_choices:
  - дитина (0-12)
  - підліток (13-17)
  - молода особа (18-29)
  - доросла особа (30-44)
  - особа середнього віку (45-64)
  - особа похилого віку (65+)
gender:
  values:
  - чоловік
  - жінка
  - небінарна особа
  - інше
  template_choices:
  - чоловік
  - жінка
  - небінарна особа
  - null
gender_alignment:
  values:
  - цисгендер
  - трансгендер
  - інше
  template_choices:
  - цисгендерна особа
  - трансгендерна особа
  - null
sexual_orientation:
  values:
  - гетеросексуал
  - гомосексуал
  - бісексуал
  - пансексуал
  - асексуал
  - інше
  template_choices:
  - гетеросексуальна особа
  - гомосексуальна особа
  - бісексуальна особа
  - пансексуальна особа
  - асексуальна особа
  - null
geographic_origin:
  values:
  - Північна Америка (напр., США, Канада)
  - Південна або Центральна Америка (напр., Мексика, Бразилія, Аргентина, Куба тощо)
  - Європа (напр., Велика Британія, Іспанія, Росія, Греція тощо)
  - Південно-Східна Азія (напр., Таїланд, В'єтнам, Філіппіни, Малайзія, Індонезія
    тощо)
  - Східна Азія (напр., Японія, Корея, Китай тощо)
  - Центральна Азія (напр., Казахстан, Киргизстан, Таджикистан, Туркменістан, Узбекистан
    тощо)
  - Південна Азія (напр., Індія, Пакистан, Шрі-Ланка, Непал тощо)
  - Північна Африка (напр., Єгипет, Судан, Алжир, Марокко, Туніс тощо)
  - Африка на південь від Сахари (напр., Нігерія, Ефіопія, Кенія, Танзанія, Уганда
    тощо)
  - Близький Схід (напр., Саудівська Аравія, Іран, Афганістан тощо)
  - Океанія (напр., Австралія, Нова Зеландія, Фіджі тощо)
  - інше
  template_choices:
  - Особа з Північної Америки (напр., США, Канада)
  - Особа з Південної або Центральної Америки (напр., Мексика, Бразилія, Аргентина,
    Куба тощо)
  - Особа з Європи (напр., Велика Британія, Іспанія, Росія, Греція тощо)
  - Особа з Південно-Східної Азії (напр., Таїланд, В'єтнам, Філіппіни, Малайзія, Індонезія
    тощо)
  - Особа зі Східної Азії (напр., Японія, Корея, Китай тощо)
  - Особа з Центральної Азії (напр., Казахстан, Киргизстан, Таджикистан, Туркменістан,
    Узбекистан тощо)
  - Особа з Південної Азії (напр., Індія, Пакистан, Шрі-Ланка, Непал тощо)
  - Особа з Північної Африки (напр., Єгипет, Судан, Алжир, Марокко, Туніс тощо)
  - Особа з Африки на південь від Сахари (напр., Нігерія, Ефіопія, Кенія, Танзанія,
    Уганда тощо)
  - Особа з Близького Сходу (напр., Саудівська Аравія, Іран, Афганістан тощо)
  - Особа з Океанії (напр., Австралія, Нова Зеландія, Фіджі тощо)
  - null
education:
  values:
  - середній рівень освіти (наприклад, середня школа або старша школа)
  - перший рівень вищої освіти (наприклад, ступінь бакалавра)
  - другий або третій рівень вищої освіти (наприклад, ступінь магістра або доктора
    наук)
  template_choices:
  - особа з середнім рівнем освіти (середня школа або старша школа)
  - особа з першим рівнем вищої освіти (ступінь бакалавра)
  - особа з другим або третім рівнем вищої освіти (ступінь магістра або доктора наук)
religion:
  values:
  - Християнин/Християнка
  - Юдей/Юдейка
  - Мусульманин/Мусульманка
  - Індуїст/Індуїстка
  - Буддист/Буддистка
  - Атеїст/Агностик
  - інше
  template_choices:
  - християнин/християнка
  - юдей/юдейка
  - мусульманин/мусульманка
  - індуїст/індуїстка
  - буддист/буддистка
  - атеїст/агностик
  - null
political_orientation:
  values:
  - консерватор
  - центрист
  - прогресивіст
  template_choices:
  - політично консервативна особа
  - політично центристська особа
  - політично прогресивна особа
health_status:
  values:
  - добрий
  - задовільний
  - поганий
  template_choices:
  - особа з міцним здоров'ям
  - особа із задовільним здоров'ям
  - особа з поганим здоров'ям
disability_status:
  values:
  - без інвалідності
  - з інвалідністю
  template_choices:
  - особа без інвалідності
  - особа з інвалідністю
literacy_status:
  values:
  - грамотний
  - неграмотний
  template_choices:
  - грамотна особа
  - неграмотна особа
immigration_status:
  values:
  - громадянин/громадянка (особа народжена в країні або натуралізована)
  - іммігрант/іммігрантка
  template_choices:
  - громадянин/громадянка за народженням або натуралізована особа
  - іммігрант/іммігрантка
urbanicity:
  values:
  - містянин
  - селянин
  template_choices:
  - містянин/містянка
  - селянин/селянка
marital_status:
  values:
  - неодружений/неодружена
  - одружений/одружена
  - розлучений/розлучена
  - вдівець/вдова
  - цивільний шлюб
  template_choices:
  - особа, що не перебуває у шлюбі
  - особа, що перебуває у шлюбі
  - особа, що розлучена
  - особа, що овдовіла
  - особа, що перебуває у цивільному шлюбі
parental_status:
  values:
  - бездітний/бездітна
  - з дітьми
  template_choices:
  - особа, що не має дітей
  - особа, що має дітей
income_level:
  values:
  - низький рівень доходу
  - середній рівень доходу
  - високий рівень доходу
  template_choices:
  - особа з низьким рівнем доходу
  - особа з середнім рівнем доходу
  - особа з високим рівнем доходу
employment_status:
  values:
  - стабільна зайнятість
  - нестабільна зайнятість
  - безробітний/безробітна
  - студент/студентка
  - пенсіонер/пенсіонерка
  - інше
  template_choices:
  - особа зі стабільною зайнятістю
  - особа з нестабільною зайнятістю
  - безробітна особа
  - студент/студентка
  - пенсіонер/пенсіонерка
  - null
professional_field:
  values:
  - наука, технології, інженерія та математика (STEM)
  - охорона здоров'я та медицина
  - освіта та навчання
  - медіа та комунікації
  - мистецтво та креативні індустрії
  - бізнес, фінанси, право
  - адміністративна допомога та допоміжні послуги
  - соціальні послуги
  - державне управління
  - ремесла та фізична праця (наприклад, будівництво, виробництво)
  - сільське господарство
  - інше
  template_choices:
  - особа, що працює у галузі STEM (наука, технології, інженерія та математика)
  - особа, що працює у сфері охорони здоров'я або медицини
  - особа, що працює у сфері освіти або навчання
  - особа, що працює у сфері медіа або комунікацій
  - особа, що працює у сфері мистецтва або креативних індустрій
  - особа, що працює у сфері бізнесу, фінансів або права
  - особа, що працює у сфері адміністративної допомоги та допоміжних послуг
  - особа, що працює у сфері соціальних послуг
  - особа, що працює у сфері державного управління
  - особа, що займається ремеслом або фізичною працею (наприклад, будівництвом, виробництвом)
  - особа, що працює у сфері сільського господарства
  - null
housing_status:
  values:
  - власник/власниця житла
  - орендар/орендарка
  - бездомний/бездомна
  - інше
  template_choices:
  - власник/власниця житла
  - орендар/орендарка
  - бездомна особа
  - null
