age:
  values:
  - बच्चा (0-12)
  - किशोर (13-17)
  - युवा (18-29)
  - वयस्क (30-44)
  - अधेड़ (45-64)
  - वरिष्ठ (65+)
  template_choices:
  - एक बच्चा / एक बच्ची (0-12)
  - एक किशोर (13-17)
  - एक युवा / एक युवती (18-29)
  - एक वयस्क (30-44)
  - एक अधेड़ उम्र का व्यक्ति (45-64)
  - एक वरिष्ठ नागरिक (65+)
gender:
  values:
  - पुरुष
  - महिला
  - नॉन-बाइनरी
  - अन्य
  template_choices:
  - एक पुरुष
  - एक महिला
  - एक नॉन-बाइनरी व्यक्ति
  - null
gender_alignment:
  values:
  - सिसजेंडर
  - ट्रांसजेंडर
  - अन्य
  template_choices:
  - एक सिसजेंडर व्यक्ति
  - एक ट्रांसजेंडर व्यक्ति
  - null
sexual_orientation:
  values:
  - विषमलिंगी
  - समलिंगी
  - उभयलिंगी
  - पैनसेक्सुअल
  - अलैंगिक
  - अन्य
  template_choices:
  - एक विषमलिंगी व्यक्ति
  - एक समलिंगी व्यक्ति
  - एक उभयलिंगी व्यक्ति
  - एक पैनसेक्सुअल व्यक्ति
  - एक अलैंगिक व्यक्ति
  - null
geographic_origin:
  values:
  - उत्तरी अमेरिका (जैसे संयुक्त राज्य अमेरिका, कनाडा)
  - दक्षिण या मध्य अमेरिका (जैसे मैक्सिको, ब्राज़ील, अर्जेंटीना, क्यूबा, आदि)
  - यूरोप (जैसे यूनाइटेड किंगडम, स्पेन, रूस, ग्रीस, आदि)
  - दक्षिण पूर्वी एशिया (जैसे थाईलैंड, वियतनाम, फिलीपींस, मलेशिया, इंडोनेशिया, आदि)
  - पूर्वी एशिया (जैसे जापान, कोरिया, चीन, आदि)
  - मध्य एशिया (जैसे कजाकिस्तान, किर्गिस्तान, ताजिकिस्तान, तुर्कमेनिस्तान, उज्बेकिस्तान,
    आदि)
  - दक्षिण एशिया (जैसे भारत, पाकिस्तान, श्रीलंका, नेपाल, आदि)
  - उत्तरी अफ्रीका (जैसे मिस्र, सूडान, अल्जीरिया, मोरक्को, ट्यूनीशिया, आदि)
  - उप-सहारा अफ्रीका (जैसे नाइजीरिया, इथियोपिया, केन्या, तंजानिया, युगांडा, आदि)
  - मध्य पूर्व (जैसे सऊदी अरब, ईरान, अफगानिस्तान, आदि)
  - ओशिनिया (जैसे ऑस्ट्रेलिया, न्यूजीलैंड, फिजी, आदि)
  - अन्य
  template_choices:
  - उत्तरी अमेरिका (जैसे संयुक्त राज्य अमेरिका, कनाडा) से एक व्यक्ति
  - दक्षिण या मध्य अमेरिका (जैसे मैक्सिको, ब्राज़ील, अर्जेंटीना, क्यूबा, आदि) से एक
    व्यक्ति
  - यूरोप (जैसे यूनाइटेड किंगडम, स्पेन, रूस, ग्रीस, आदि) से एक व्यक्ति
  - दक्षिण पूर्वी एशिया (जैसे थाईलैंड, वियतनाम, फिलीपींस, मलेशिया, इंडोनेशिया, आदि)
    से एक व्यक्ति
  - पूर्वी एशिया (जैसे जापान, कोरिया, चीन, आदि) से एक व्यक्ति
  - मध्य एशिया (जैसे कजाकिस्तान, किर्गिस्तान, ताजिकिस्तान, तुर्कमेनिस्तान, उज्बेकिस्तान,
    आदि) से एक व्यक्ति
  - दक्षिण एशिया (जैसे भारत, पाकिस्तान, श्रीलंका, नेपाल, आदि) से एक व्यक्ति
  - उत्तरी अफ्रीका (जैसे मिस्र, सूडान, अल्जीरिया, मोरक्को, ट्यूनीशिया, आदि) से एक
    व्यक्ति
  - उप-सहारा अफ्रीका (जैसे नाइजीरिया, इथियोपिया, केन्या, तंजानिया, युगांडा, आदि) से
    एक व्यक्ति
  - मध्य पूर्व (जैसे सऊदी अरब, ईरान, अफगानिस्तान, आदि) से एक व्यक्ति
  - ओशिनिया (जैसे ऑस्ट्रेलिया, न्यूजीलैंड, फिजी, आदि) से एक व्यक्ति
  - null
education:
  values:
  - बुनियादी (e.g. less than high school, or high school)
  - ग्रेजुएट (e.g. bachelor's degree, some college)
  - स्नातकोत्तर (e.g. master's degree, doctoral degree)
  template_choices:
  - बुनियादी शिक्षा प्राप्त व्यक्ति (less than high school, or high school)
  - ग्रेजुएट व्यक्ति (bachelor's degree or some college)
  - स्नातकोत्तर शिक्षा प्राप्त व्यक्ति (master's degree or doctoral degree)
religion:
  values:
  - ईसाई
  - यहूदी
  - मुस्लिम
  - हिंदू
  - बौद्ध
  - नास्तिक/अज्ञेयवादी
  - अन्य
  template_choices:
  - एक ईसाई व्यक्ति
  - यहूदी धर्म का व्यक्ति
  - एक मुस्लिम व्यक्ति
  - एक हिंदू व्यक्ति
  - एक बौद्ध व्यक्ति
  - एक नास्तिक
  - null
political_orientation:
  values:
  - रूढ़िवादी
  - मध्यमार्गी
  - प्रगतिशील
  template_choices:
  - एक राजनीतिक रूप से रूढ़िवादी व्यक्ति
  - एक राजनीतिक रूप से मध्यमार्गी व्यक्ति
  - एक राजनीतिक रूप से प्रगतिशील व्यक्ति
health_status:
  values:
  - अच्छा
  - सामान्य
  - खराब
  template_choices:
  - स्वस्थ व्यक्ति
  - सामान्य स्वास्थ्य वाला व्यक्ति
  - अस्वस्थ व्यक्ति
disability_status:
  values:
  - कोई विकलांगता नहीं
  - कुछ विकलांगता
  template_choices:
  - सक्षम व्यक्ति
  - विकलांग व्यक्ति
literacy_status:
  values:
  - साक्षर
  - निरक्षर
  template_choices:
  - एक साक्षर व्यक्ति
  - एक निरक्षर व्यक्ति
immigration_status:
  values:
  - नागरिक (जन्मजात या देशीयकृत)
  - आप्रवासी
  template_choices:
  - एक जन्मजात या देशीयकृत नागरिक
  - एक आप्रवासी
urbanicity:
  values:
  - शहरी
  - ग्रामीण
  template_choices:
  - एक शहरी व्यक्ति
  - एक ग्रामीण व्यक्ति
marital_status:
  values:
  - अविवाहित
  - विवाहित
  - तलाकशुदा या अलग
  - विधवा/विधुर
  - घरेलू साझेदारी
  template_choices:
  - एक अविवाहित व्यक्ति
  - एक विवाहित व्यक्ति
  - एक तलाकशुदा या अलग हुआ व्यक्ति
  - एक विधवा/विधुर
  - एक घरेलू साझेदारी में रहने वाला व्यक्ति
parental_status:
  values:
  - निस्संतान
  - बच्चों के साथ
  template_choices:
  - एक निस्संतान व्यक्ति
  - एक बच्चों वाला व्यक्ति
income_level:
  values:
  - निम्न आय
  - मध्यम आय
  - उच्च आय
  template_choices:
  - निम्न आय वाला व्यक्ति
  - मध्यम आय वाला व्यक्ति
  - उच्च आय वाला व्यक्ति
employment_status:
  values:
  - स्थायी रोजगार
  - अस्थिर रोजगार
  - बेरोजगार
  - विद्यार्थी
  - सेवानिवृत्त
  - अन्य
  template_choices:
  - स्थायी रोजगार वाला व्यक्ति
  - अस्थिर रोजगार वाला व्यक्ति
  - एक बेरोजगार व्यक्ति
  - एक विद्यार्थी
  - एक सेवानिवृत्त व्यक्ति
  - null
professional_field:
  values:
  - विज्ञान, प्रौद्योगिकी, इंजीनियरिंग और गणित (STEM)
  - स्वास्थ्य सेवा और चिकित्सा
  - शिक्षा और प्रशिक्षण
  - मीडिया और संचार
  - कला और रचनात्मक उद्योग
  - व्यवसाय, वित्त, कानूनी
  - प्रशासनिक सहायता और समर्थन सेवाएँ
  - सामाजिक सेवाएँ
  - लोक प्रशासन
  - ट्रेड और शारीरिक श्रम (e.g. construction, manufacturing)
  - कृषि
  - अन्य
  template_choices:
  - STEM क्षेत्र (विज्ञान, प्रौद्योगिकी, इंजीनियरिंग और गणित) में काम करने वाला व्यक्ति
  - स्वास्थ्य सेवा या चिकित्सा में काम करने वाला व्यक्ति
  - शिक्षा या प्रशिक्षण में काम करने वाला व्यक्ति
  - मीडिया या संचार में काम करने वाला व्यक्ति
  - कला या रचनात्मक उद्योगों में काम करने वाला व्यक्ति
  - व्यवसाय, वित्त या कानूनी क्षेत्र में काम करने वाला व्यक्ति
  - प्रशासनिक सहायता और समर्थन सेवाओं में काम करने वाला व्यक्ति
  - सामाजिक सेवाओं में काम करने वाला व्यक्ति
  - लोक प्रशासन में काम करने वाला व्यक्ति
  - ट्रेड या शारीरिक श्रम (e.g. construction, manufacturing) में काम करने वाला व्यक्ति
  - कृषि में काम करने वाला व्यक्ति or किसान
  - null
housing_status:
  values:
  - मकान मालिक
  - किरायेदार
  - बेघर
  - अन्य
  template_choices:
  - एक मकान मालिक
  - एक किरायेदार
  - एक बेघर व्यक्ति
  - null
