age:
  values:
  - طفل (٠-١٢)
  - مراهق (١٣-١٧)
  - شاب (١٨-٢٩)
  - بالغ (٣٠-٤٤)
  - متوسط العمر (٤٥-٦٤)
  - مسن (٦٥+)
  template_choices:
  - طفل أو طفلة (٠-١٢)
  - مراهق أو مراهقة (١٣-١٧)
  - شاب أو شابة (١٨-٢٩)
  - بالغ أو بالغة (٣٠-٤٤)
  - شخص في منتصف العمر (٤٥-٦٤)
  - مسن أو مسنّة (٦٥+)
gender:
  values:
  - رجل
  - امرأة
  - غير ثنائي الجنس
  - آخر
  template_choices:
  - رجل
  - امرأة
  - شخص غير ثنائي أو ثنائية الجنس
  - null
gender_alignment:
  values:
  - متوافق جنسيًا
  - متحول جنسيًا
  - آخر
  template_choices:
  - شخص متوافق أو متوافقة جنسيًا
  - شخص متحول أو متحولة جنسيًا
  - null
sexual_orientation:
  values:
  - مغاير جنسياً
  - مثلي جنسياً
  - مزدوج الميول الجنسية
  - جامع الميول الجنسية
  - لاجنسي
  - آخر
  template_choices:
  - شخص مغايرأو مغايرة جنسياً
  - شخص ثنائي او ثنائية الميول الجنسية
  - شخص مزدوج أو مزدوجة الميول الجنسية
  - شخص مُتعدّد أو مُتعدّدة الميول الجنسية
  - شخص لاجنسي
  - null
geographic_origin:
  values:
  - أمريكا الشمالية (مثل الولايات المتحدة، كندا)
  - أمريكا الجنوبية أو الوسطى (مثل المكسيك، البرازيل، الأرجنتين، كوبا، إلخ)
  - أوروبا (مثل المملكة المتحدة، إسبانيا، روسيا، اليونان، إلخ)
  - جنوب شرق آسيا (مثل تايلاند، فيتنام، الفلبين، ماليزيا، إندونيسيا، إلخ)
  - شرق آسيا (مثل اليابان، كوريا، الصين، إلخ)
  - آسيا الوسطى (مثل كازاخستان، قيرغيزستان، طاجيكستان، تركمانستان، أوزبكستان، إلخ)
  - جنوب آسيا (مثل الهند، باكستان، سريلانكا، نيبال، إلخ)
  - شمال أفريقيا (مثل مصر، السودان، الجزائر، المغرب، تونس، إلخ)
  - أفريقيا جنوب الصحراء الكبرى (مثل نيجيريا، إثيوبيا، كينيا، تنزانيا، أوغندا، إلخ)
  - الشرق الأوسط (مثل المملكة العربية السعودية، إيران، أفغانستان، إلخ)
  - أوقيانوسيا (مثل أستراليا، نيوزيلندا، فيجي، إلخ)
  - أخرى
  template_choices:
  - شخص من أمريكا الشمالية (مثل الولايات المتحدة، كندا)
  - شخص من أمريكا الجنوبية أو الوسطى (مثل المكسيك، البرازيل، الأرجنتين، كوبا، إلخ)
  - شخص من أوروبا (مثل المملكة المتحدة، إسبانيا، روسيا، اليونان، إلخ)
  - شخص من جنوب شرق آسيا (مثل تايلاند، فيتنام، الفلبين، ماليزيا، إندونيسيا، إلخ)
  - شخص من شرق آسيا (مثل اليابان، كوريا، الصين، إلخ)
  - شخص من آسيا الوسطى (مثل كازاخستان، قيرغيزستان، طاجيكستان، تركمانستان، أوزبكستان،
    إلخ)
  - شخص من جنوب آسيا (مثل الهند، باكستان، سريلانكا، نيبال، إلخ)
  - شخص من شمال أفريقيا (مثل مصر، السودان، الجزائر، المغرب، تونس، إلخ)
  - شخص من أفريقيا جنوب الصحراء الكبرى (مثل نيجيريا، إثيوبيا، كينيا، تنزانيا، أوغندا،
    إلخ)
  - شخص من الشرق الأوسط (مثل المملكة العربية السعودية، إيران، أفغانستان، إلخ)
  - شخص من أوقيانوسيا (مثل أستراليا، نيوزيلندا، فيجي، إلخ)
  - null
education:
  values:
  - 'أساسي (مثلاً: أقل من الثانوية، أو ثانوية)'
  - 'جامعي (مثلاً: بكالوريوس، أو دراسة جامعية)'
  - 'دراسات عليا (مثلاً: ماجستير، أو دكتوراه)'
  template_choices:
  - شخص بـتعليم أساسي (أقل من الثانوية أو ثانوية)
  - شخص بـتعليم جامعي (بكالوريوس أو دراسة جامعية)
  - شخص بـدراسات عليا (ماجستير أو دكتوراه)
religion:
  values:
  - مسيحي
  - شخص من الديانة اليهودية
  - مسلم
  - هندوسي
  - بوذي
  - ملحد/لاأدري
  - آخر
  template_choices:
  - مسيحي أو مسيحية
  - يهودي أو يهودية
  - مسلم أو مسلمة
  - هندوسي أو هندوسية
  - بوذي أو بوذية
  - شخص بدون ديانه
  - null
political_orientation:
  values:
  - محافظ
  - وسطي
  - تقدمي
  template_choices:
  - شخص بـتوجه سياسي محافظ
  - شخص بـتوجه سياسي وسطي
  - شخص بـتوجه سياسي تقدمي
health_status:
  values:
  - جيدة
  - متوسطة
  - سيئة
  template_choices:
  - شخص بصحة جيدة
  - شخص بصحة متوسطة
  - شخص بصحة سيئة
disability_status:
  values:
  - بدون إعاقة
  - لديه إعاقة
  template_choices:
  - شخص بدون إعاقة
  - شخص بإعاقة
literacy_status:
  values:
  - متعلم
  - أمي
  template_choices:
  - شخص متعلم
  - شخص بـوضعية أميّة
immigration_status:
  values:
  - مواطن بالولادة أو بالتجنيس
  - مهاجر
  template_choices:
  - مواطن أو مواطنة بالولادة أو بالتجنيس
  - مهاجر أو مهاجرة
urbanicity:
  values:
  - حضري
  - ريفي
  template_choices:
  - شخص حضري
  - شخص ريفي
marital_status:
  values:
  - أعزب
  - متزوج
  - مطلق أو منفصل
  - أرمل
  - شراكة منزلية
  template_choices:
  - شخص بدون زواج
  - شخص في زواج
  - شخص مطلق أو مطلقة أو منفصل أو منفصلة
  - شخص أرمل أو أرملة
  - شخص في شراكة منزلية
parental_status:
  values:
  - بدون أطفال
  - لديه أطفال
  template_choices:
  - شخص بدون أطفال
  - شخص  بأطفال
income_level:
  values:
  - دخل منخفض
  - دخل متوسط
  - دخل مرتفع
  template_choices:
  - شخص بـدخل منخفض
  - شخص بـدخل متوسط
  - شخص بـدخل مرتفع
employment_status:
  values:
  - عمل مستقر
  - عمل مؤقت
  - عاطل عن العمل
  - طالب
  - متقاعد
  - آخر
  template_choices:
  - شخص بـعمل مستقر
  - شخص بـعمل مؤقت
  - شخص بدون عمل
  - طالب أو طالب
  - شخص في تقاعد
  - null
professional_field:
  values:
  - 'العلوم والتكنولوجيا والهندسة والرياضيات (مثلاً: البرمجة، الهندسة، البحث العلمي)'
  - الرعاية الصحية والطب
  - التعليم والتدريب
  - الإعلام والاتصال
  - الفنون والصناعات الإبداعية
  - الأعمال والمالية والقانون
  - المساعدة الإدارية وخدمات الدعم
  - الخدمات الاجتماعية
  - الإدارة العامة
  - 'الحرف والعمل اليدوي (مثلاً: البناء، التصنيع)'
  - الزراعة
  - آخر
  template_choices:
  - شخص بـمهنة في مجالات العلوم والتكنولوجيا والهندسة والرياضيات
  - شخص بـمهنة الرعاية الصحية أو الطب
  - شخص بـمهنة التعليم أو التدريب
  - شخص بـمهنة الإعلام أو الاتصال
  - شخص بـمهنة الفنون أو الصناعات الإبداعية
  - شخص بـمهنة الأعمال أو المالية أو القانون
  - شخص بـمهنة المساعدة الإدارية وخدمات الدعم
  - شخص بـمهنة الخدمات الاجتماعية
  - شخص بـمهنة الإدارة العامة
  - شخص بـمهنة في الحرف أو العمل اليدوي (البناء، التصنيع)
  - شخص بـمهنة الزراعة
  - null
housing_status:
  values:
  - صاحب منزل
  - مستأجر
  - بلا مأوى
  - آخر
  template_choices:
  - صاحب أو صاحبة منزل
  - مستأجر أو مستأجرة
  - شخص بلا مأوى
  - null
