age:
  values:
  - 儿童 (0-12)
  - 青少年 (13-17)
  - 年轻人 (18-29)
  - 成年人 (30-44)
  - 中年人 (45-64)
  - 老年人 (65+)
  template_choices:
  - 一名儿童 (0-12)
  - 一名青少年 (13-17)
  - 一名年轻人 (18-29)
  - 一名成年人 (30-44)
  - 一名中年人 (45-64)
  - 一名老年人 (65+)
gender:
  values:
  - 男性
  - 女性
  - 非二元性别
  - 其他
  template_choices:
  - 一个男人
  - 一个女人
  - 一个非二元性别者
  - null
gender_alignment:
  values:
  - 顺性别
  - 跨性别
  - 其他
  template_choices:
  - 一位顺性别者
  - 一位跨性别者
  - null
sexual_orientation:
  values:
  - 异性恋
  - 同性恋
  - 双性恋
  - 泛性恋
  - 无性恋
  - 其他
  template_choices:
  - 一位异性恋者
  - 一位同性恋者
  - 一位双性恋者
  - 一位泛性恋者
  - 一位无性恋者
  - null
geographic_origin:
  values:
  - 北美洲（例如：美国、加拿大）
  - 中南美洲（例如：墨西哥、巴西、阿根廷、古巴等）
  - 欧洲（例如英国、西班牙、俄罗斯、希腊等）
  - 东南亚（例如：泰国、越南、菲律宾、马来西亚、印度尼西亚等）
  - 东亚（例如：日本、韩国、中国等）
  - 中亚（例如：哈萨克斯坦、吉尔吉斯斯坦、塔吉克斯坦、土库曼斯坦、乌兹别克斯坦等）
  - 南亚（例如：印度、巴基斯坦、斯里兰卡、尼泊尔等）
  - 北非（例如：埃及、苏丹、阿尔及利亚、摩洛哥、突尼斯等）
  - 撒哈拉以南非洲（例如：尼日利亚、埃塞俄比亚、肯尼亚、坦桑尼亚、乌干达等）
  - 中东（例如：沙特阿拉伯、伊朗、阿富汗等）
  - 大洋洲（例如：澳大利亚、新西兰、斐济等）
  - 其他
  template_choices:
  - 来自北美洲的人（例如：美国、加拿大）
  - 来自中南美洲的人（例如：墨西哥、巴西、阿根廷、古巴等）
  - 来自欧洲的人（例如英国、西班牙、俄罗斯、希腊等）
  - 来自东南亚的人（例如：泰国、越南、菲律宾、马来西亚、印度尼西亚等）
  - 来自东亚的人（例如：日本、韩国、中国等）
  - 来自中亚的人（例如：哈萨克斯坦、吉尔吉斯斯坦、塔吉克斯坦、土库曼斯坦、乌兹别克斯坦等）
  - 来自南亚的人（例如：印度、巴基斯坦、斯里兰卡、尼泊尔等）
  - 来自北非的人（例如：埃及、苏丹、阿尔及利亚、摩洛哥、突尼斯等）
  - 来自撒哈拉以南非洲的人（例如：尼日利亚、埃塞俄比亚、肯尼亚、坦桑尼亚、乌干达等）
  - 来自中东的人（例如：沙特阿拉伯、伊朗、阿富汗等）
  - 来自大洋洲的人（例如：澳大利亚、新西兰、斐济等）
  - null
education:
  values:
  - 基础教育 (e.g. less than high school, or high school)
  - 本科教育 (e.g. bachelor's degree, some college)
  - 研究生教育 (e.g. master's degree, doctoral degree)
  template_choices:
  - 一个受过基础教育的人 (高中前或者高中)
  - 一个受过大学教育的人 (本科学位或者专科)
  - 一个受过研究生教育的人 (硕士学位或者博士学位)
religion:
  values:
  - 基督徒
  - 犹太教徒
  - 穆斯林
  - 印度教徒
  - 佛教徒
  - 无神论者/不可知论者
  - 其他
  template_choices:
  - 一位基督徒
  - 一名犹太教徒
  - 一位穆斯林
  - 一位印度教徒
  - 一位佛教徒
  - 一位无神论者/不可知论者
  - null
political_orientation:
  values:
  - 保守派
  - 中间派
  - 进步派
  template_choices:
  - 一个政治保守的人
  - 一个政治中间派
  - 一个政治进步的人
health_status:
  values:
  - 良好
  - 一般
  - 差
  template_choices:
  - 一个健康状况良好的人
  - 一个健康状况一般的人
  - 一个健康状况差的人
disability_status:
  values:
  - 无残疾
  - 有残疾
  template_choices:
  - 一个非残疾人
  - 一个残疾人
literacy_status:
  values:
  - 识字
  - 文盲
  template_choices:
  - 一个识字的人
  - 一个文盲
immigration_status:
  values:
  - 公民 (native-born or naturalized)
  - 移民
  template_choices:
  - 一位本土出生或归化入籍的公民
  - 一位移民
urbanicity:
  values:
  - 城市
  - 乡村
  template_choices:
  - 一个城市人
  - 一个乡村人
marital_status:
  values:
  - 单身
  - 已婚
  - 离异或分居
  - 丧偶
  - 同居伴侣关系
  template_choices:
  - 一位单身人士
  - 一位已婚人士
  - 一位离异或分居人士
  - 一位丧偶人士
  - 一位有同居伴侣的人
parental_status:
  values:
  - 无子女
  - 有子女
  template_choices:
  - 一位无子女的人
  - 一位有子女的人
income_level:
  values:
  - 低收入
  - 中等收入
  - 高收入
  template_choices:
  - 一个低收入者
  - 一个中等收入者
  - 一个高收入者
employment_status:
  values:
  - 稳定就业
  - 不稳定就业
  - 失业
  - 学生
  - 退休
  - 其他
  template_choices:
  - 一位拥有稳定工作的人
  - 一位工作不稳定的人
  - 一位失业者
  - 一名学生
  - 一位退休人员
  - null
professional_field:
  values:
  - 科学、技术、工程和数学 (STEM)
  - 医疗保健和医学
  - 教育和培训
  - 媒体和传播
  - 艺术和创意产业
  - 商业、金融、法律
  - 行政协助和支持服务
  - 社会服务
  - 公共行政
  - 技工和体力劳动 (e.g. construction, manufacturing)
  - 农业
  - 其他
  template_choices:
  - 一名在 STEM 领域（科学、技术、工程和数学）工作的人
  - 一名在医疗保健或医学领域工作的人
  - 一名在教育或培训领域工作的人
  - 一名在媒体或传播领域工作的人
  - 一名在艺术或创意产业工作的人
  - 一名在商业、金融或法律领域工作的人
  - 一名在行政协助和支持服务领域工作的人
  - 一名在社会服务领域工作的人
  - 一名在公共行政领域工作的人
  - 一名从事技术工作或体力劳动 (例如，建筑行业、制造业) 的人
  - 一名在农业领域工作的人
  - null
housing_status:
  values:
  - 房主
  - 租客
  - 无家可归者
  - 其他
  template_choices:
  - 一位房主
  - 一位租客
  - 一位无家可归者
  - null
