misconduct:
- ذهاب إلى السجن
- اعتقال بسبب القيادة تحت تأثير الكحول
- سرقة متجر بقالة
- غش في امتحان
hobbies:
- ممارسة لعبة الشطرنج
- حضور حفل موسيقي
- ممارسة الجولف
- ممارسة كرة القدم
learning:
- الالتحاق بالدراسة الجامعية
- الاطلاع على مواد متعلقة بتنمية المهارات الشخصية
- التسجيل في دورة لتعلّم لغة جديدة
- حضور جلسة تعليمية في الطهي
social_and_family:
- تنأول عشاءً عائليًا
- مواساة صديقًا في حداد
- خروج مع بعض الأصدقاء
- ذهاب إلى حفلة
financial:
- الاستثمار في سوق الأسهم
- شراء منزل عطلة فاخر
- التقديم للحصول على قسائم الطعام
- المكافحه لتوفير لقمة العيش
technology_and_maintenance:
- إصلاح جهاز كمبيوتر معطلً
- معاناة في الاتصال بالإنترنت
- استبدال شمعات الإشعال
- بناء مخزن حديقة
activism:
- المشاركة في احتجاج
- جمع النفايات على الشاطئ
- الذهاب إلى تجمع سياسي
- توزيع منشورات للانتخابات المحلية
health:
- الذهاب إلى المستشفى
- شراء الأدوية من الصيدلية
- المعاناة من ألم مزمن
- إجراء فحص دم
conflict_and_crisis:
- التعرض لحادث سيارة
- إجراء الإسعافات الأولية
- التصادم مع الجار
- المناقشة الحادة مع زميل في العمل
