misconduct:
- allant en prison
- se faisant arrêter pour conduite en état d'ivresse
- braquant une épicerie
- trichant à un examen
hobbies:
- jouant aux échecs
- allant à un concert
- jouant au golf
- jouant au football
learning:
- étudiant à l'université
- lisant sur le développement personnel
- s'inscrivant à un nouveau cours de langue
- assistant à un cours de cuisine
social_and_family:
- dînant en famille
- réconfortant un ami en deuil
- sortant avec des amis
- allant à une fête
financial:
- investissant en bourse
- achetant une maison de vacances de luxe
- demandant des bons alimentaires
- ayant du mal à boucler ses fins de mois
technology_and_maintenance:
- réparant un ordinateur cassé
- ayant du mal à se connecter à internet
- changeant une bougie d'allumage
- construisant un abri de jardin
activism:
- participant à une manifestation
- ramassant des déchets sur la plage
- allant à un rassemblement politique
- distribuant des tracts pour une élection locale
health:
- allant à l'hôpital
- achetant des médicaments à la pharmacie
- souffrant de douleurs chroniques
- faisant une prise de sang
conflict_and_crisis:
- ayant un accident de voiture
- administrant les premiers secours
- se disputant avec un voisin
- se disputant avec un collègue
