misconduct:
- indo para a cadeia
- sendo presa por dirigir embriagada
- assaltando um mercado
- colando em uma prova
hobbies:
- jogando xadrez
- indo a um show
- jogando golfe
- jogando futebol
learning:
- estudando na faculdade
- lendo sobre desenvolvimento pessoal
- se matriculando em um curso de idiomas
- participando de uma aula de culinária
social_and_family:
- jantando em família
- consolando um amigo de luto
- saindo com alguns amigos
- indo a uma festa
financial:
- investindo na bolsa de valores
- comprando uma casa de férias de luxo
- solicitando auxílio-alimentação
- tendo dificuldades pra pagar as contas
technology_and_maintenance:
- consertando um computador quebrado
- tendo dificuldades para se conectar à internet
- trocando uma vela de ignição
- construindo um galpão de jardim
activism:
- participando de um protesto
- recolhendo lixo na praia
- indo a um comício político
- distribuindo panfletos para uma eleição local
health:
- indo para o hospital
- comprando remédios em uma farmácia
- sofrendo de dor crônica
- fazendo um exame de sangue
conflict_and_crisis:
- se envolvendo em um acidente de carro
- prestando primeiros socorros
- confrontando um vizinho
- discutindo com um colega de trabalho
