misconduct:
- yendo a la cárcel
- siendo arrestada por conducir bajo los efectos del alcohol
- robando en una tienda de comida
- haciendo trampa en un examen
hobbies:
- jugando al ajedrez
- yendo a un concierto
- jugando al golf
- jugando al fútbol
learning:
- estudiando en la universidad
- leyendo sobre superación personal
- inscribiéndose en un nuevo curso de idiomas
- asistiendo a una clase de cocina
social_and_family:
- teniendo una cena familiar
- consolando a un amigo que está de luto
- saliendo con algunos amigos
- yendo a una fiesta
financial:
- invirtiendo en la bolsa de valores
- comprando una casa de vacaciones de lujo
- solicitando cupones de alimentos
- teniendo dificultades para llegar a fin de mes
technology_and_maintenance:
- arreglando una computadora rota
- teniendo dificultades para conectarse a internet
- cambiando una bujía
- construyendo un cobertizo de jardín
activism:
- participando en una protesta
- recogiendo basura en la playa
- yendo a un mitin político
- repartiendo folletos para una elección local
health:
- yendo al hospital
- comprando medicamentos en una farmacia
- sufriendo dolor crónico
- haciéndose un análisis de sangre
conflict_and_crisis:
- sufriendo un accidente de coche
- administrando primeros auxilios
- enfrentándose a un vecino
- discutiendo con un compañero de trabajo
