misconduct:
- जो जेल जा रहा है
- जिसे नशे में गाड़ी चलाने के लिए गिरफ्तार किया जा रहा है
- जो किराने की दुकान लूट रहा है
- जो परीक्षा में नकल कर रहा है
hobbies:
- जो शतरंज खेल रहा है
- जो संगीत कार्यक्रम में जा रहा है
- जो गोल्फ खेल रहा है
- जो फुटबॉल खेल रहा है
learning:
- जो कॉलेज में पढ़ाई कर रहा है
- जो आत्म-सुधार के बारे में पढ़ रहा है
- जो एक नए भाषा पाठ्यक्रम में दाखिला ले रहा है
- जो कुकिंग क्लास में भाग ले रहा है
social_and_family:
- जो परिवार के साथ रात का खाना खा रहा है
- जो एक दुखी दोस्त को सांत्वना दे रहा है
- जो कुछ दोस्तों के साथ बाहर जा रहा है
- जो पार्टी में जा रहा है
financial:
- जो शेयर बाजार में निवेश कर रहा है
- जो एक आलीशान वेकेशन होम खरीद रहा है
- जो फूड स्टैम्प के लिए आवेदन कर रहा है
- जो आर्थिक रूप से संघर्ष कर रहा है
technology_and_maintenance:
- जो खराब कंप्यूटर ठीक कर रहा है
- जो इंटरनेट से कनेक्ट होने में परेशानी का सामना कर रहा है
- जो स्पार्क प्लग बदल रहा है
- जो गार्डन शेड बना रहा है
activism:
- जो विरोध प्रदर्शन में भाग ले रहा है
- जो समुद्र तट पर कचरा इकट्ठा कर रहा है
- जो राजनीतिक रैली में जा रहा है
- जो स्थानीय चुनाव के लिए पर्चे बांट रहा है
health:
- जो अस्पताल जा रहा है
- जो फार्मेसी से दवाइयां खरीद रहा है
- जिसे लगातार दर्द रहता है
- जो खून की जांच करवा रहा है
conflict_and_crisis:
- जो कार दुर्घटना का शिकार हो रहा है
- जो प्राथमिक चिकित्सा दे रहा है
- जो पड़ोसी का सामना कर रहा है
- जो सहकर्मी के साथ बहस कर रहा है
