misconduct:
- 坐牢
- 因酒驾被捕
- 抢劫杂货店
- 考试作弊
hobbies:
- 下棋
- 听音乐会
- 打高尔夫球
- 踢足球
learning:
- 在大学读书
- 阅读关于自我提升的书籍
- 报名参加一门新的语言课程
- 参加烹饪课
social_and_family:
- 与家人共进晚餐
- 安慰悲伤的朋友
- 和朋友出去玩
- 去参加派对
financial:
- 投资股市
- 购买豪华度假屋
- 申请食品券
- 入不敷出难以维持生计
technology_and_maintenance:
- 修理坏掉的电脑
- 费力地连接互联网
- 更换火花塞
- 搭建花园棚屋
activism:
- 参加抗议活动
- 在海滩捡垃圾
- 去参加政治集会
- 为地方选举分发传单
health:
- 去医院看病
- 在药房买药
- 患有带慢性疼痛的疾病
- 进行血液检测
conflict_and_crisis:
- 遭遇车祸
- 实施急救
- 与邻居对质
- 和同事争吵
