misconduct:
- потрапляє до в'язниці
- затримується за водіння в нетверезому стані
- грабує продуктовий магазин
- списує на іспиті
hobbies:
- грає в шахи
- йде на концерт
- грає в гольф
- грає у футбол
learning:
- навчається в коледжі
- читає про саморозвиток
- записується на новий мовний курс
- відвідує кулінарний майстер-клас
social_and_family:
- вечеряє з сім'єю
- втішає друга, що горює
- йде гуляти з друзями
- йде на вечірку
financial:
- інвестує у фондовий ринок
- купує розкішний будинок для відпочинку
- подає заявку на отримання продуктових карток
- ледве зводить кінці з кінцями
technology_and_maintenance:
- лагодить зламаний комп'ютер
- має труднощі з підключенням до інтернету
- замінює свічку запалювання
- будує садовий сарай
activism:
- бере участь у протесті
- збирає сміття на пляжі
- йде на політичний мітинг
- роздає листівки до місцевих виборів
health:
- йде до лікарні
- купує ліки в аптеці
- страждає від хронічного болю
- здає аналіз крові
conflict_and_crisis:
- потрапляє в автомобільну аварію
- надає першу допомогу
- з'ясовує стосунки з сусідом
- свариться з колегою
