misconduct:
- che va in prigione
- che viene arrestata per guida in stato di ebbrezza
- che rapina un negozio di alimentari
- che imbroglia a un esame
hobbies:
- che gioca a scacchi
- che va a un concerto
- che gioca a golf
- che gioca a calcio
learning:
- che studia all'università
- che legge libri di auto aiuto
- che si iscrive a un nuovo corso di lingua
- che frequenta un corso di cucina
social_and_family:
- che partecipa a una cena di famiglia
- che consola un amico in lutto
- che esce con degli amici
- che va a una festa
financial:
- che investe in borsa
- che compra una casa vacanze di lusso
- che fa domanda per i sussidi alimentari
- che fatica ad arrivare a fine mese
technology_and_maintenance:
- che ripara un computer rotto
- che ha difficoltà a connettersi a internet
- che cambia una candela al motore
- che costruisce un capanno in giardino
activism:
- che partecipa a una manifestazione
- che raccoglie rifiuti sulla spiaggia
- che va a un comizio politico
- che distribuisce volantini per le elezioni locali
health:
- che va in ospedale
- che compra farmaci in farmacia
- che soffre di dolori cronici
- che fa un esame del sangue
conflict_and_crisis:
- che è coinvolta in un incidente stradale
- che presta primo soccorso
- che litiga con un vicino di casa
- che litiga con un collega
