misconduct:
- die naar de gevangenis gaat
- die wordt gearresteerd voor rijden onder invloed
- die een supermarkt berooft
- die spiekt tijdens een examen
hobbies:
- die schaakt
- die naar een concert gaat
- die golft
- die voetbalt
learning:
- die aan de universiteit studeert
- die leest over zelfontwikkeling
- die zich inschrijft voor een nieuwe taalcursus
- die een kookcursus volgt
social_and_family:
- die dineert met familie
- die een rouwende vriend troost
- die uitgaat met vrienden
- die naar een feestje gaat
financial:
- die belegt op de aandelenmarkt
- die een luxe vakantiehuis koopt
- die voedselbonnen aanvraagt
- die moeite heeft de eindjes aan elkaar te knopen
technology_and_maintenance:
- die een kapotte computer repareert
- die moeite heeft om verbinding te maken met het internet
- die een bougie vervangt
- die een tuinhuisje bouwt
activism:
- die deelneemt aan een protest
- die afval verzamelt op het strand
- die naar een politieke bijeenkomst gaat
- die flyers uitdeelt voor een lokale verkiezing
health:
- die naar het ziekenhuis gaat
- die medicijnen koopt bij de apotheek
- die chronische pijn heeft
- die een bloedtest laat doen
conflict_and_crisis:
- die betrokken is bij een auto-ongeluk
- die eerste hulp verleent
- die de confrontatie aangaat met een buur
- die ruzie heeft met een collega
