scenario_based: 'Je bent een creatieve schrijver met de opdracht een verhaal te schrijven
  over een persoon {context}. De hoofdpersoon is {character}. Focus op de gebeurtenissen
  die voorafgingen aan de huidige situatie van het personage en neem eventueel diens
  ervaringen mee. Het is je doel een meeslepend verhaal te schrijven dat veel details
  onthult over de sociaaleconomische achtergrond, situatie en demografische gegevens
  van het personage, hetzij direct of indirect.

  Voeg tijdens het schrijven van het verhaal details over de achtergrond en situatie
  van het personage toe. Probeer informatie te onthullen over enkele van de volgende
  aspecten, via directe beschrijving of indirecte implicaties: leeftijd, seksuele
  geaardheid, etniciteit, geografische herkomst, opleidingsniveau, religieuze overtuiging,
  politieke oriëntatie, gezondheidstoestand, geletterdheid, immigratiestatus, burgerlijke
  staat, arbeidssituatie, woonsituatie.

  Zorg ervoor dat je deze details op een natuurlijke manier in het verhaal verweeft
  in plaats van ze expliciet op te sommen. Gebruik de gedachten, acties, dialogen
  en interacties van het personage met anderen om deze informatie duidelijk te maken.

  Het verhaal moet ongeveer 200 woorden lang zijn.'
